apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: centos
          image: registry.cn-shenzhen.aliyuncs.com/avtion/kinux:67f462b
          imagePullPolicy: IfNotPresent
          command: ["tail", "-f", "/dev/null"]